import pandas as pd
import matplotlib.pyplot as plt
import re
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_ollama import ChatOllama


class ChartAgent:
    def __init__(self, df: pd.DataFrame):
        self.df = df
        self.llm = ChatOllama(
            model="qwen2.5-coder:7b",
            temperature=0
        )

        template = """
You are a strict Python data visualization agent.

User question:
{question}

DataFrame info:
- Numeric columns: {numeric_cols}
- Datetime columns: {datetime_cols}
- Categorical columns: {categorical_cols}

Data types: {dtypes}

First 5 rows: {head}

Examples:
- Raw Data (Ticket List): df['Status'].value_counts().plot(kind='bar')
- Pre-Aggregated (SQL Group By): plt.bar(df['Category'], df['Count'])

Rules (MANDATORY):
1. Use ONLY matplotlib.pyplot as plt
2. Use ONLY the existing DataFrame `df`
3. Create EXACTLY ONE chart
4. No imports, no file access, no loops
5. Always set title, xlabel, ylabel
6. Prevent overlapped labels: plt.xticks(rotation=45, ha='right') if many categories
7. If data is PRE-AGGREGATED (Check if a 'Count' or numeric metric column exists), plot values DIRECTLY.
8. Always end with plt.show()
9. If no meaningful chart is possible, return: print("No suitable chart")

Return ONLY valid Python code.
"""

        self.prompt = PromptTemplate.from_template(template)
        self.chain = self.prompt | self.llm | StrOutputParser()

    def _is_safe_code(self, code: str) -> bool:
        forbidden = [
            "import", "open(", "exec(", "eval(",
            "while ", "for ", "__", "os.", "sys."
        ]
        return not any(word in code for word in forbidden)

    def plot(self, question: str) -> bool:
        try:
            if self.df.empty:
                print("Chart Agent: DataFrame is empty.")
                return False

            numeric_cols = self.df.select_dtypes(include="number").columns.tolist()
            datetime_cols = self.df.select_dtypes(include="datetime").columns.tolist()
            categorical_cols = self.df.select_dtypes(exclude=["number", "datetime"]).columns.tolist()

            plot_code = self.chain.invoke({
                "question": question,
                "numeric_cols": numeric_cols,
                "datetime_cols": datetime_cols,
                "categorical_cols": categorical_cols,
                "dtypes": str(self.df.dtypes),
                "head": self.df.head().to_string()
            }).strip()

            # Clean markdown fences
            plot_code = re.sub(r"```.*?```", "", plot_code, flags=re.S).strip()

            if not self._is_safe_code(plot_code):
                raise ValueError("Unsafe code generated by LLM")

            print("Chart Agent: Executing chart...")
            exec_globals = {"df": self.df, "plt": plt, "pd": pd}
            exec(plot_code, exec_globals)
            plt.close("all")

            print("Chart displayed successfully.")
            return True

        except Exception as e:
            print(f"Chart Agent Error: {e}")
            return False
